### ISSUE TITLE
Errors in Plotting Data from a Field Campaign (TRACER)

### ISSUE THREAD

**Issue by jukent** [ProjectPythiaCookbooks/radar-cookbook#66]
Plotting Data from a Field Campaign (TRACER) has lots of various errors rendering on the site.

https://cookbooks.projectpythia.org/radar-cookbook/notebooks/example-workflows/tracer-example.html

Starrung with a TypeError that likely proliferates. Should our build checks catch things like this?

**Comment by brian-rose** [comment]
Related: https://github.com/ProjectPythiaCookbooks/cookbook-template/issues/53

**Comment by mgrover1** [comment]
It's stemming from the notebook not having access to the data since it can't read in the credentials. Also, we wouldn't be able to check this in the PR process since PRs do not have access to Github secrets...
